//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpdrachtService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Opdracht", Namespace="http://schemas.datacontract.org/2004/07/MLSWebServices.DataContracts")]
    public partial class Opdracht : object
    {
        
        private int AantalColliField;
        
        private string ArtikelField;
        
        private string ArtikelNrField;
        
        private string BeginLocatieNrField;
        
        private string BeginLocatieNrDisplayField;
        
        private string ControleNummerField;
        
        private string ControleNummer2Field;
        
        private string EindLocatieNrField;
        
        private string EindLocatieNrDisplayField;
        
        private string GebiedField;
        
        private double GewichtField;
        
        private string IdnrField;
        
        private string InbehandelingDoorPincodeField;
        
        private bool IsBestemmingAnderGebiedField;
        
        private bool IsBestemmingPickLocatieField;
        
        private bool IsOudeOpdrachtField;
        
        private string LastDragerField;
        
        private string OpdrachtNummerField;
        
        private int OpdrachtenAfgerondField;
        
        private int OpdrachtenOpenField;
        
        private int OpdrachtenOpenOrderField;
        
        private string PalletNummerNaarField;
        
        private string PalletNummerVanField;
        
        private OpdrachtService.PartijStatus PartijStatusField;
        
        private OpdrachtService.OpdrachtStatus StatusField;
        
        private string StatusOmschrijvingField;
        
        private OpdrachtService.OpdrachtType TypeField;
        
        private string ZonegroepNrField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AantalColli
        {
            get
            {
                return this.AantalColliField;
            }
            set
            {
                this.AantalColliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Artikel
        {
            get
            {
                return this.ArtikelField;
            }
            set
            {
                this.ArtikelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArtikelNr
        {
            get
            {
                return this.ArtikelNrField;
            }
            set
            {
                this.ArtikelNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeginLocatieNr
        {
            get
            {
                return this.BeginLocatieNrField;
            }
            set
            {
                this.BeginLocatieNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeginLocatieNrDisplay
        {
            get
            {
                return this.BeginLocatieNrDisplayField;
            }
            set
            {
                this.BeginLocatieNrDisplayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ControleNummer
        {
            get
            {
                return this.ControleNummerField;
            }
            set
            {
                this.ControleNummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ControleNummer2
        {
            get
            {
                return this.ControleNummer2Field;
            }
            set
            {
                this.ControleNummer2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EindLocatieNr
        {
            get
            {
                return this.EindLocatieNrField;
            }
            set
            {
                this.EindLocatieNrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EindLocatieNrDisplay
        {
            get
            {
                return this.EindLocatieNrDisplayField;
            }
            set
            {
                this.EindLocatieNrDisplayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gebied
        {
            get
            {
                return this.GebiedField;
            }
            set
            {
                this.GebiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Gewicht
        {
            get
            {
                return this.GewichtField;
            }
            set
            {
                this.GewichtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idnr
        {
            get
            {
                return this.IdnrField;
            }
            set
            {
                this.IdnrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InbehandelingDoorPincode
        {
            get
            {
                return this.InbehandelingDoorPincodeField;
            }
            set
            {
                this.InbehandelingDoorPincodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBestemmingAnderGebied
        {
            get
            {
                return this.IsBestemmingAnderGebiedField;
            }
            set
            {
                this.IsBestemmingAnderGebiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBestemmingPickLocatie
        {
            get
            {
                return this.IsBestemmingPickLocatieField;
            }
            set
            {
                this.IsBestemmingPickLocatieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOudeOpdracht
        {
            get
            {
                return this.IsOudeOpdrachtField;
            }
            set
            {
                this.IsOudeOpdrachtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastDrager
        {
            get
            {
                return this.LastDragerField;
            }
            set
            {
                this.LastDragerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpdrachtNummer
        {
            get
            {
                return this.OpdrachtNummerField;
            }
            set
            {
                this.OpdrachtNummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OpdrachtenAfgerond
        {
            get
            {
                return this.OpdrachtenAfgerondField;
            }
            set
            {
                this.OpdrachtenAfgerondField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OpdrachtenOpen
        {
            get
            {
                return this.OpdrachtenOpenField;
            }
            set
            {
                this.OpdrachtenOpenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OpdrachtenOpenOrder
        {
            get
            {
                return this.OpdrachtenOpenOrderField;
            }
            set
            {
                this.OpdrachtenOpenOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PalletNummerNaar
        {
            get
            {
                return this.PalletNummerNaarField;
            }
            set
            {
                this.PalletNummerNaarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PalletNummerVan
        {
            get
            {
                return this.PalletNummerVanField;
            }
            set
            {
                this.PalletNummerVanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OpdrachtService.PartijStatus PartijStatus
        {
            get
            {
                return this.PartijStatusField;
            }
            set
            {
                this.PartijStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OpdrachtService.OpdrachtStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusOmschrijving
        {
            get
            {
                return this.StatusOmschrijvingField;
            }
            set
            {
                this.StatusOmschrijvingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OpdrachtService.OpdrachtType Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZonegroepNr
        {
            get
            {
                return this.ZonegroepNrField;
            }
            set
            {
                this.ZonegroepNrField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartijStatus", Namespace="http://schemas.datacontract.org/2004/07/MLSWebServices.DataContracts")]
    public enum PartijStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartijOnbekend = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartijAfgekeurd = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArtikelNietNodig = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArtikelOnbekend = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeenPicklocatie = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeenPallet = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PalletGeenBelading = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PalletLeeg = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartijInQuarantaine = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpdrachtStatus", Namespace="http://schemas.datacontract.org/2004/07/MLSWebServices.DataContracts")]
    public enum OpdrachtStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Beschikbaar = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PalletOnbekend = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReedsInMagazijn = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NietBeschikbaar = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BuitenGebied = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeenOrderGevonden = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrderGeblokkeerd = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BeginlocatieOnbekend = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EindlocatieOnbekend = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EindlocatieBezet = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PalletGeenBeladingsregels = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArtikelOnbekend = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeenInslag = 12,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpdrachtType", Namespace="http://schemas.datacontract.org/2004/07/MLSWebServices.DataContracts")]
    public enum OpdrachtType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inslag = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uitslag = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tel = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aanvul = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transport = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Retour = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GTM = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fabriek = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weegkeuken = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultaatOfOpdracht5SlwlhPY", Namespace="http://schemas.datacontract.org/2004/07/MLSWebServices.DataContracts")]
    public partial class ResultaatOfOpdracht5SlwlhPY : object
    {
        
        private string FoutmeldingField;
        
        private bool IsValideField;
        
        private OpdrachtService.Opdracht ResultaatObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foutmelding
        {
            get
            {
                return this.FoutmeldingField;
            }
            set
            {
                this.FoutmeldingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValide
        {
            get
            {
                return this.IsValideField;
            }
            set
            {
                this.IsValideField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OpdrachtService.Opdracht ResultaatObject
        {
            get
            {
                return this.ResultaatObjectField;
            }
            set
            {
                this.ResultaatObjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resultaat", Namespace="http://schemas.datacontract.org/2004/07/MLSWebServices.DataContracts")]
    public partial class Resultaat : object
    {
        
        private string FoutmeldingField;
        
        private bool IsValideField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foutmelding
        {
            get
            {
                return this.FoutmeldingField;
            }
            set
            {
                this.FoutmeldingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValide
        {
            get
            {
                return this.IsValideField;
            }
            set
            {
                this.IsValideField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultaatOfArrayOfWeegkeukenAanvoerOpdracht5SlwlhPY", Namespace="http://schemas.datacontract.org/2004/07/MLSWebServices.DataContracts")]
    public partial class ResultaatOfArrayOfWeegkeukenAanvoerOpdracht5SlwlhPY : object
    {
        
        private string FoutmeldingField;
        
        private bool IsValideField;
        
        private OpdrachtService.WeegkeukenAanvoerOpdracht[] ResultaatObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foutmelding
        {
            get
            {
                return this.FoutmeldingField;
            }
            set
            {
                this.FoutmeldingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValide
        {
            get
            {
                return this.IsValideField;
            }
            set
            {
                this.IsValideField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OpdrachtService.WeegkeukenAanvoerOpdracht[] ResultaatObject
        {
            get
            {
                return this.ResultaatObjectField;
            }
            set
            {
                this.ResultaatObjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeegkeukenAanvoerOpdracht", Namespace="http://schemas.datacontract.org/2004/07/MLSWebServices.DataContracts")]
    public partial class WeegkeukenAanvoerOpdracht : object
    {
        
        private string ControlenummerField;
        
        private long IdField;
        
        private string NaarLocatienaamField;
        
        private int NaarLocatienummerField;
        
        private long PalletnummerField;
        
        private string PincodeField;
        
        private string StatusField;
        
        private string VanLocatienaamField;
        
        private int VanLocatienummerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Controlenummer
        {
            get
            {
                return this.ControlenummerField;
            }
            set
            {
                this.ControlenummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NaarLocatienaam
        {
            get
            {
                return this.NaarLocatienaamField;
            }
            set
            {
                this.NaarLocatienaamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NaarLocatienummer
        {
            get
            {
                return this.NaarLocatienummerField;
            }
            set
            {
                this.NaarLocatienummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Palletnummer
        {
            get
            {
                return this.PalletnummerField;
            }
            set
            {
                this.PalletnummerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pincode
        {
            get
            {
                return this.PincodeField;
            }
            set
            {
                this.PincodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VanLocatienaam
        {
            get
            {
                return this.VanLocatienaamField;
            }
            set
            {
                this.VanLocatienaamField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VanLocatienummer
        {
            get
            {
                return this.VanLocatienummerField;
            }
            set
            {
                this.VanLocatienummerField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultaatOfWeegkeukenAanvoerOpdracht5SlwlhPY", Namespace="http://schemas.datacontract.org/2004/07/MLSWebServices.DataContracts")]
    public partial class ResultaatOfWeegkeukenAanvoerOpdracht5SlwlhPY : object
    {
        
        private string FoutmeldingField;
        
        private bool IsValideField;
        
        private OpdrachtService.WeegkeukenAanvoerOpdracht ResultaatObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Foutmelding
        {
            get
            {
                return this.FoutmeldingField;
            }
            set
            {
                this.FoutmeldingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValide
        {
            get
            {
                return this.IsValideField;
            }
            set
            {
                this.IsValideField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OpdrachtService.WeegkeukenAanvoerOpdracht ResultaatObject
        {
            get
            {
                return this.ResultaatObjectField;
            }
            set
            {
                this.ResultaatObjectField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OpdrachtService.IOpdrachtService")]
    public interface IOpdrachtService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/CheckService", ReplyAction="http://tempuri.org/IOpdrachtService/CheckServiceResponse")]
        System.Threading.Tasks.Task<bool> CheckServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/GeefVolgendeOpdracht", ReplyAction="http://tempuri.org/IOpdrachtService/GeefVolgendeOpdrachtResponse")]
        System.Threading.Tasks.Task<OpdrachtService.Opdracht> GeefVolgendeOpdrachtAsync(string truckNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/StartInslagOpdracht", ReplyAction="http://tempuri.org/IOpdrachtService/StartInslagOpdrachtResponse")]
        System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> StartInslagOpdrachtAsync(string pin, string palletNummer, string gebied);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/StartInslagOpdrachtLocatieBepalingLES", ReplyAction="http://tempuri.org/IOpdrachtService/StartInslagOpdrachtLocatieBepalingLESResponse" +
            "")]
        System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> StartInslagOpdrachtLocatieBepalingLESAsync(string pin, string palletNummer, string gebied, bool locatiebepalingGMAG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/StartUitslagOpdracht", ReplyAction="http://tempuri.org/IOpdrachtService/StartUitslagOpdrachtResponse")]
        System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> StartUitslagOpdrachtAsync(string pin, OpdrachtService.Opdracht opdracht);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/StartTransportOpdracht", ReplyAction="http://tempuri.org/IOpdrachtService/StartTransportOpdrachtResponse")]
        System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> StartTransportOpdrachtAsync(string pin, OpdrachtService.Opdracht opdracht);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/StartGTMOpdracht", ReplyAction="http://tempuri.org/IOpdrachtService/StartGTMOpdrachtResponse")]
        System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> StartGTMOpdrachtAsync(string pin, OpdrachtService.Opdracht opdracht);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/StartAanvulOpdracht", ReplyAction="http://tempuri.org/IOpdrachtService/StartAanvulOpdrachtResponse")]
        System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> StartAanvulOpdrachtAsync(string pin, OpdrachtService.Opdracht opdracht);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/AanvulOpdrachtPalletIngevuld", ReplyAction="http://tempuri.org/IOpdrachtService/AanvulOpdrachtPalletIngevuldResponse")]
        System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> AanvulOpdrachtPalletIngevuldAsync(string pin, OpdrachtService.Opdracht opdracht);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/InslagOpdrachtAfronden", ReplyAction="http://tempuri.org/IOpdrachtService/InslagOpdrachtAfrondenResponse")]
        System.Threading.Tasks.Task InslagOpdrachtAfrondenAsync(OpdrachtService.Opdracht opdracht);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/AanvulOpdrachtAfronden", ReplyAction="http://tempuri.org/IOpdrachtService/AanvulOpdrachtAfrondenResponse")]
        System.Threading.Tasks.Task AanvulOpdrachtAfrondenAsync(OpdrachtService.Opdracht opdracht, int colliAantalEindlocatie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/TransportOpdrachtAfronden", ReplyAction="http://tempuri.org/IOpdrachtService/TransportOpdrachtAfrondenResponse")]
        System.Threading.Tasks.Task TransportOpdrachtAfrondenAsync(OpdrachtService.Opdracht opdracht);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/GTMOpdrachtAfronden", ReplyAction="http://tempuri.org/IOpdrachtService/GTMOpdrachtAfrondenResponse")]
        System.Threading.Tasks.Task GTMOpdrachtAfrondenAsync(OpdrachtService.Opdracht opdracht);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/UitslagOpdrachtAfronden", ReplyAction="http://tempuri.org/IOpdrachtService/UitslagOpdrachtAfrondenResponse")]
        System.Threading.Tasks.Task UitslagOpdrachtAfrondenAsync(OpdrachtService.Opdracht opdracht);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/UitslagOpdrachtMarkeren", ReplyAction="http://tempuri.org/IOpdrachtService/UitslagOpdrachtMarkerenResponse")]
        System.Threading.Tasks.Task UitslagOpdrachtMarkerenAsync(string opdrachtNummer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/OntkoppelOpdracht", ReplyAction="http://tempuri.org/IOpdrachtService/OntkoppelOpdrachtResponse")]
        System.Threading.Tasks.Task OntkoppelOpdrachtAsync(OpdrachtService.Opdracht opdracht);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/OpdrachtOntkoppelen", ReplyAction="http://tempuri.org/IOpdrachtService/OpdrachtOntkoppelenResponse")]
        System.Threading.Tasks.Task OpdrachtOntkoppelenAsync(string opdrachtNummer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/MaakOpdrachtVoorMagazijnMutatie", ReplyAction="http://tempuri.org/IOpdrachtService/MaakOpdrachtVoorMagazijnMutatieResponse")]
        System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> MaakOpdrachtVoorMagazijnMutatieAsync(string palletnummer, string gebied, string pin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/LocatieVrijgeven", ReplyAction="http://tempuri.org/IOpdrachtService/LocatieVrijgevenResponse")]
        System.Threading.Tasks.Task LocatieVrijgevenAsync(string locatienr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/FabriekopdrachtStarten", ReplyAction="http://tempuri.org/IOpdrachtService/FabriekopdrachtStartenResponse")]
        System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> FabriekopdrachtStartenAsync(long orderaanvoerOpdrachtId, string gebied, string pincode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/FabriekopdrachtAnnuleren", ReplyAction="http://tempuri.org/IOpdrachtService/FabriekopdrachtAnnulerenResponse")]
        System.Threading.Tasks.Task<OpdrachtService.Resultaat> FabriekopdrachtAnnulerenAsync(string opdrachtnummer, string pincode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/FabriekopdrachtAfronden", ReplyAction="http://tempuri.org/IOpdrachtService/FabriekopdrachtAfrondenResponse")]
        System.Threading.Tasks.Task<OpdrachtService.Resultaat> FabriekopdrachtAfrondenAsync(string opdrachtnummer, string pincode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/WeegkeukenGeefOpenstaandeopdrachten", ReplyAction="http://tempuri.org/IOpdrachtService/WeegkeukenGeefOpenstaandeopdrachtenResponse")]
        System.Threading.Tasks.Task<OpdrachtService.ResultaatOfArrayOfWeegkeukenAanvoerOpdracht5SlwlhPY> WeegkeukenGeefOpenstaandeopdrachtenAsync(string pincode, int[] locatienummersNaar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/WeegkeukenopdrachtStarten", ReplyAction="http://tempuri.org/IOpdrachtService/WeegkeukenopdrachtStartenResponse")]
        System.Threading.Tasks.Task<OpdrachtService.ResultaatOfWeegkeukenAanvoerOpdracht5SlwlhPY> WeegkeukenopdrachtStartenAsync(long opdrachtId, string pincode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/WeegkeukenopdrachtAnnuleren", ReplyAction="http://tempuri.org/IOpdrachtService/WeegkeukenopdrachtAnnulerenResponse")]
        System.Threading.Tasks.Task<OpdrachtService.Resultaat> WeegkeukenopdrachtAnnulerenAsync(long opdrachtId, string pincode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOpdrachtService/WeegkeukenopdrachtAfronden", ReplyAction="http://tempuri.org/IOpdrachtService/WeegkeukenopdrachtAfrondenResponse")]
        System.Threading.Tasks.Task<OpdrachtService.Resultaat> WeegkeukenopdrachtAfrondenAsync(long opdrachtId, string pincode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IOpdrachtServiceChannel : OpdrachtService.IOpdrachtService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class OpdrachtServiceClient : System.ServiceModel.ClientBase<OpdrachtService.IOpdrachtService>, OpdrachtService.IOpdrachtService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OpdrachtServiceClient() : 
                base(OpdrachtServiceClient.GetDefaultBinding(), OpdrachtServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IOpdrachtService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OpdrachtServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(OpdrachtServiceClient.GetBindingForEndpoint(endpointConfiguration), OpdrachtServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OpdrachtServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OpdrachtServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OpdrachtServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OpdrachtServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OpdrachtServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> CheckServiceAsync()
        {
            return base.Channel.CheckServiceAsync();
        }
        
        public System.Threading.Tasks.Task<OpdrachtService.Opdracht> GeefVolgendeOpdrachtAsync(string truckNumber)
        {
            return base.Channel.GeefVolgendeOpdrachtAsync(truckNumber);
        }
        
        public System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> StartInslagOpdrachtAsync(string pin, string palletNummer, string gebied)
        {
            return base.Channel.StartInslagOpdrachtAsync(pin, palletNummer, gebied);
        }
        
        public System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> StartInslagOpdrachtLocatieBepalingLESAsync(string pin, string palletNummer, string gebied, bool locatiebepalingGMAG)
        {
            return base.Channel.StartInslagOpdrachtLocatieBepalingLESAsync(pin, palletNummer, gebied, locatiebepalingGMAG);
        }
        
        public System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> StartUitslagOpdrachtAsync(string pin, OpdrachtService.Opdracht opdracht)
        {
            return base.Channel.StartUitslagOpdrachtAsync(pin, opdracht);
        }
        
        public System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> StartTransportOpdrachtAsync(string pin, OpdrachtService.Opdracht opdracht)
        {
            return base.Channel.StartTransportOpdrachtAsync(pin, opdracht);
        }
        
        public System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> StartGTMOpdrachtAsync(string pin, OpdrachtService.Opdracht opdracht)
        {
            return base.Channel.StartGTMOpdrachtAsync(pin, opdracht);
        }
        
        public System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> StartAanvulOpdrachtAsync(string pin, OpdrachtService.Opdracht opdracht)
        {
            return base.Channel.StartAanvulOpdrachtAsync(pin, opdracht);
        }
        
        public System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> AanvulOpdrachtPalletIngevuldAsync(string pin, OpdrachtService.Opdracht opdracht)
        {
            return base.Channel.AanvulOpdrachtPalletIngevuldAsync(pin, opdracht);
        }
        
        public System.Threading.Tasks.Task InslagOpdrachtAfrondenAsync(OpdrachtService.Opdracht opdracht)
        {
            return base.Channel.InslagOpdrachtAfrondenAsync(opdracht);
        }
        
        public System.Threading.Tasks.Task AanvulOpdrachtAfrondenAsync(OpdrachtService.Opdracht opdracht, int colliAantalEindlocatie)
        {
            return base.Channel.AanvulOpdrachtAfrondenAsync(opdracht, colliAantalEindlocatie);
        }
        
        public System.Threading.Tasks.Task TransportOpdrachtAfrondenAsync(OpdrachtService.Opdracht opdracht)
        {
            return base.Channel.TransportOpdrachtAfrondenAsync(opdracht);
        }
        
        public System.Threading.Tasks.Task GTMOpdrachtAfrondenAsync(OpdrachtService.Opdracht opdracht)
        {
            return base.Channel.GTMOpdrachtAfrondenAsync(opdracht);
        }
        
        public System.Threading.Tasks.Task UitslagOpdrachtAfrondenAsync(OpdrachtService.Opdracht opdracht)
        {
            return base.Channel.UitslagOpdrachtAfrondenAsync(opdracht);
        }
        
        public System.Threading.Tasks.Task UitslagOpdrachtMarkerenAsync(string opdrachtNummer)
        {
            return base.Channel.UitslagOpdrachtMarkerenAsync(opdrachtNummer);
        }
        
        public System.Threading.Tasks.Task OntkoppelOpdrachtAsync(OpdrachtService.Opdracht opdracht)
        {
            return base.Channel.OntkoppelOpdrachtAsync(opdracht);
        }
        
        public System.Threading.Tasks.Task OpdrachtOntkoppelenAsync(string opdrachtNummer)
        {
            return base.Channel.OpdrachtOntkoppelenAsync(opdrachtNummer);
        }
        
        public System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> MaakOpdrachtVoorMagazijnMutatieAsync(string palletnummer, string gebied, string pin)
        {
            return base.Channel.MaakOpdrachtVoorMagazijnMutatieAsync(palletnummer, gebied, pin);
        }
        
        public System.Threading.Tasks.Task LocatieVrijgevenAsync(string locatienr)
        {
            return base.Channel.LocatieVrijgevenAsync(locatienr);
        }
        
        public System.Threading.Tasks.Task<OpdrachtService.ResultaatOfOpdracht5SlwlhPY> FabriekopdrachtStartenAsync(long orderaanvoerOpdrachtId, string gebied, string pincode)
        {
            return base.Channel.FabriekopdrachtStartenAsync(orderaanvoerOpdrachtId, gebied, pincode);
        }
        
        public System.Threading.Tasks.Task<OpdrachtService.Resultaat> FabriekopdrachtAnnulerenAsync(string opdrachtnummer, string pincode)
        {
            return base.Channel.FabriekopdrachtAnnulerenAsync(opdrachtnummer, pincode);
        }
        
        public System.Threading.Tasks.Task<OpdrachtService.Resultaat> FabriekopdrachtAfrondenAsync(string opdrachtnummer, string pincode)
        {
            return base.Channel.FabriekopdrachtAfrondenAsync(opdrachtnummer, pincode);
        }
        
        public System.Threading.Tasks.Task<OpdrachtService.ResultaatOfArrayOfWeegkeukenAanvoerOpdracht5SlwlhPY> WeegkeukenGeefOpenstaandeopdrachtenAsync(string pincode, int[] locatienummersNaar)
        {
            return base.Channel.WeegkeukenGeefOpenstaandeopdrachtenAsync(pincode, locatienummersNaar);
        }
        
        public System.Threading.Tasks.Task<OpdrachtService.ResultaatOfWeegkeukenAanvoerOpdracht5SlwlhPY> WeegkeukenopdrachtStartenAsync(long opdrachtId, string pincode)
        {
            return base.Channel.WeegkeukenopdrachtStartenAsync(opdrachtId, pincode);
        }
        
        public System.Threading.Tasks.Task<OpdrachtService.Resultaat> WeegkeukenopdrachtAnnulerenAsync(long opdrachtId, string pincode)
        {
            return base.Channel.WeegkeukenopdrachtAnnulerenAsync(opdrachtId, pincode);
        }
        
        public System.Threading.Tasks.Task<OpdrachtService.Resultaat> WeegkeukenopdrachtAfrondenAsync(long opdrachtId, string pincode)
        {
            return base.Channel.WeegkeukenopdrachtAfrondenAsync(opdrachtId, pincode);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOpdrachtService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOpdrachtService))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.2.27:8080/OpdrachtService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OpdrachtServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IOpdrachtService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OpdrachtServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IOpdrachtService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IOpdrachtService,
        }
    }
}
